language: ruby
rvm:
- 2.4
dist: trusty
sudo: false
gemfile: ".travis.gemfile"
env:
- CONCEPTQL_DATA_MODEL=omopv4_plus CONCEPTQL_FORCE_TEMP_TABLES=false SEQUELIZER_URI="postgres://localhost/test_data_for_jigsaw?search_path=omopv4_plus_250&username=postgres"
- CONCEPTQL_DATA_MODEL=gdm CONCEPTQL_FORCE_TEMP_TABLES=false SEQUELIZER_URI="postgres://localhost/test_data_for_jigsaw?search_path=gdm_250&username=postgres"
- CONCEPTQL_DATA_MODEL=omopv4_plus CONCEPTQL_FORCE_TEMP_TABLES=true DOCKER_SCRATCH_DATABASE=jigsaw_temp SEQUELIZER_URI="postgres://localhost/test_data_for_jigsaw?search_path=omopv4_plus_250&username=postgres"
- CONCEPTQL_DATA_MODEL=gdm CONCEPTQL_FORCE_TEMP_TABLES=true DOCKER_SCRATCH_DATABASE=jigsaw_temp SEQUELIZER_URI="postgres://localhost/test_data_for_jigsaw?search_path=gdm_250&username=postgres"
addons:
  postgresql: '9.6'
  apt:
    packages:
    - python-pip
    - pigz
services:
- postgresql
before_install:
- sudo mount -o remount,size=50% /var/ramfs
- pip install --user pyOpenSSL cryptography idna certifi "urllib3[secure]" sqlparse
script: travis_wait 45 bash .travis.postgres.sh
notifications:
  slack:
    secure: YrvvLrIOgRIzqb01GbektA0YZXCieghuhaU3O4vBW/otrz26twb/0zeB/HHqKS3P2re0R127wGw6nAUAG9ieEHPYMKcpZZWzvnPrqQ/5ASbIZWX85fps0svFEeQTqRjK8TdHC/0ZJoy3P7i6wgBoWcs434aSR4K6KgisdWJATk0=

jobs:
  fast_finish: true
  include:
    - stage: Impala Test Sorted, Shuffle-joined Temp Tables, Set 1
      env: TESTS_DIV_MOD="2 0" CONCEPTQL_DATA_MODEL=omopv4_plus CONCEPTQL_FORCE_TEMP_TABLES=true DOCKER_SCRATCH_DATABASE=jigsaw_temp SEQUELIZER_URI="impala://localhost/synpuf250" CONCEPTQL_SORT_TEMP_TABLES=true CONCEPTQL_FORCE_SHUFFLE_JOINS=true
      script: travis_wait 50 bash .travis.impala.sh
    - stage: Impala Test Sorted, Shuffle-joined Temp Tables, Set 2
      env: TESTS_DIV_MOD="2 1" CONCEPTQL_DATA_MODEL=omopv4_plus CONCEPTQL_FORCE_TEMP_TABLES=true DOCKER_SCRATCH_DATABASE=jigsaw_temp SEQUELIZER_URI="impala://localhost/synpuf250" CONCEPTQL_SORT_TEMP_TABLES=true CONCEPTQL_FORCE_SHUFFLE_JOINS=true
      script: travis_wait 50 bash .travis.impala.sh
    - stage: Impala Test Sorted Temp Tables, Set 1
      env: TESTS_DIV_MOD="2 0" CONCEPTQL_DATA_MODEL=omopv4_plus CONCEPTQL_FORCE_TEMP_TABLES=true DOCKER_SCRATCH_DATABASE=jigsaw_temp SEQUELIZER_URI="impala://localhost/synpuf250" CONCEPTQL_SORT_TEMP_TABLES=true
      script: travis_wait 50 bash .travis.impala.sh
    - stage: Impala Test Sorted Temp Tables, Set 2
      env: TESTS_DIV_MOD="2 1" CONCEPTQL_DATA_MODEL=omopv4_plus CONCEPTQL_FORCE_TEMP_TABLES=true DOCKER_SCRATCH_DATABASE=jigsaw_temp SEQUELIZER_URI="impala://localhost/synpuf250" CONCEPTQL_SORT_TEMP_TABLES=true
      script: travis_wait 50 bash .travis.impala.sh
    - stage: Impala Test Temp Tables, Set 1
      env: TESTS_DIV_MOD="2 0" CONCEPTQL_DATA_MODEL=omopv4_plus CONCEPTQL_FORCE_TEMP_TABLES=true DOCKER_SCRATCH_DATABASE=jigsaw_temp SEQUELIZER_URI="impala://localhost/synpuf250"
      script: travis_wait 50 bash .travis.impala.sh
    - stage: Impala Test Temp Tables, Set 2
      env: TESTS_DIV_MOD="2 1" CONCEPTQL_DATA_MODEL=omopv4_plus CONCEPTQL_FORCE_TEMP_TABLES=true DOCKER_SCRATCH_DATABASE=jigsaw_temp SEQUELIZER_URI="impala://localhost/synpuf250"
      script: travis_wait 50 bash .travis.impala.sh
    - stage: Impala Test No Temp Tables, Set 1
      env: TESTS_DIV_MOD="2 0" CONCEPTQL_DATA_MODEL=omopv4_plus CONCEPTQL_FORCE_TEMP_TABLES=false SEQUELIZER_URI="impala://localhost/synpuf250"
      script: travis_wait 50 bash .travis.impala.sh
    - stage: Impala Test No Temp Tables, Set 2
      env: TESTS_DIV_MOD="2 1" CONCEPTQL_DATA_MODEL=omopv4_plus CONCEPTQL_FORCE_TEMP_TABLES=false SEQUELIZER_URI="impala://localhost/synpuf250"
      script: travis_wait 50 bash .travis.impala.sh
    - stage: deploy
      before_install: gem install tping
      script:
        - tping --token $TRAVIS_PRO_TOKEN --user outcomesinsights --repo jigsaw-diagram-editor --pro --branch $TRAVIS_BRANCH
        - tping --token $TRAVIS_PRO_TOKEN --user outcomesinsights --repo t_shank --pro --branch $TRAVIS_BRANCH
  allow_failures:
    - env: TESTS_DIV_MOD="4 0" CONCEPTQL_DATA_MODEL=omopv4_plus CONCEPTQL_FORCE_TEMP_TABLES=false SEQUELIZER_URI="impala://localhost/synpuf250"
    - env: TESTS_DIV_MOD="4 1" CONCEPTQL_DATA_MODEL=omopv4_plus CONCEPTQL_FORCE_TEMP_TABLES=false SEQUELIZER_URI="impala://localhost/synpuf250"
    - env: TESTS_DIV_MOD="4 2" CONCEPTQL_DATA_MODEL=omopv4_plus CONCEPTQL_FORCE_TEMP_TABLES=false SEQUELIZER_URI="impala://localhost/synpuf250"
    - env: TESTS_DIV_MOD="4 3" CONCEPTQL_DATA_MODEL=omopv4_plus CONCEPTQL_FORCE_TEMP_TABLES=false SEQUELIZER_URI="impala://localhost/synpuf250"

    - env: TESTS_DIV_MOD="4 0" CONCEPTQL_DATA_MODEL=omopv4_plus CONCEPTQL_FORCE_TEMP_TABLES=true DOCKER_SCRATCH_DATABASE=jigsaw_temp SEQUELIZER_URI="impala://localhost/synpuf250"
    - env: TESTS_DIV_MOD="4 1" CONCEPTQL_DATA_MODEL=omopv4_plus CONCEPTQL_FORCE_TEMP_TABLES=true DOCKER_SCRATCH_DATABASE=jigsaw_temp SEQUELIZER_URI="impala://localhost/synpuf250"
    - env: TESTS_DIV_MOD="4 2" CONCEPTQL_DATA_MODEL=omopv4_plus CONCEPTQL_FORCE_TEMP_TABLES=true DOCKER_SCRATCH_DATABASE=jigsaw_temp SEQUELIZER_URI="impala://localhost/synpuf250"
    - env: TESTS_DIV_MOD="4 3" CONCEPTQL_DATA_MODEL=omopv4_plus CONCEPTQL_FORCE_TEMP_TABLES=true DOCKER_SCRATCH_DATABASE=jigsaw_temp SEQUELIZER_URI="impala://localhost/synpuf250"

    - env: TESTS_DIV_MOD="4 0" CONCEPTQL_DATA_MODEL=omopv4_plus CONCEPTQL_FORCE_TEMP_TABLES=true DOCKER_SCRATCH_DATABASE=jigsaw_temp SEQUELIZER_URI="impala://localhost/synpuf250" CONCEPTQL_SORT_TEMP_TABLES=true
    - env: TESTS_DIV_MOD="4 1" CONCEPTQL_DATA_MODEL=omopv4_plus CONCEPTQL_FORCE_TEMP_TABLES=true DOCKER_SCRATCH_DATABASE=jigsaw_temp SEQUELIZER_URI="impala://localhost/synpuf250" CONCEPTQL_SORT_TEMP_TABLES=true
    - env: TESTS_DIV_MOD="4 2" CONCEPTQL_DATA_MODEL=omopv4_plus CONCEPTQL_FORCE_TEMP_TABLES=true DOCKER_SCRATCH_DATABASE=jigsaw_temp SEQUELIZER_URI="impala://localhost/synpuf250" CONCEPTQL_SORT_TEMP_TABLES=true
    - env: TESTS_DIV_MOD="4 3" CONCEPTQL_DATA_MODEL=omopv4_plus CONCEPTQL_FORCE_TEMP_TABLES=true DOCKER_SCRATCH_DATABASE=jigsaw_temp SEQUELIZER_URI="impala://localhost/synpuf250" CONCEPTQL_SORT_TEMP_TABLES=true

    - env: TESTS_DIV_MOD="4 0" CONCEPTQL_DATA_MODEL=omopv4_plus CONCEPTQL_FORCE_TEMP_TABLES=true DOCKER_SCRATCH_DATABASE=jigsaw_temp SEQUELIZER_URI="impala://localhost/synpuf250" CONCEPTQL_SORT_TEMP_TABLES=true CONCEPTQL_FORCE_SHUFFLE_JOINS=true
    - env: TESTS_DIV_MOD="4 1" CONCEPTQL_DATA_MODEL=omopv4_plus CONCEPTQL_FORCE_TEMP_TABLES=true DOCKER_SCRATCH_DATABASE=jigsaw_temp SEQUELIZER_URI="impala://localhost/synpuf250" CONCEPTQL_SORT_TEMP_TABLES=true CONCEPTQL_FORCE_SHUFFLE_JOINS=true
    - env: TESTS_DIV_MOD="4 2" CONCEPTQL_DATA_MODEL=omopv4_plus CONCEPTQL_FORCE_TEMP_TABLES=true DOCKER_SCRATCH_DATABASE=jigsaw_temp SEQUELIZER_URI="impala://localhost/synpuf250" CONCEPTQL_SORT_TEMP_TABLES=true CONCEPTQL_FORCE_SHUFFLE_JOINS=true
    - env: TESTS_DIV_MOD="4 3" CONCEPTQL_DATA_MODEL=omopv4_plus CONCEPTQL_FORCE_TEMP_TABLES=true DOCKER_SCRATCH_DATABASE=jigsaw_temp SEQUELIZER_URI="impala://localhost/synpuf250" CONCEPTQL_SORT_TEMP_TABLES=true CONCEPTQL_FORCE_SHUFFLE_JOINS=true
