language: ruby
rvm:
  - 2.2
  - jruby
sudo: false
gemfile: .travis.gemfile
env:
  CONCEPTQL_DATA_MODEL=omopv4_plus
  SEQUELIZER_URI="postgres://localhost/synpuf_250_20160815?username=postgres"
addons:
  postgresql: "9.6"
services:
  - postgresql
before_install:
  - gem install bundler
  - psql -c 'create database synpuf_250_20160815;' -U postgres
  - curl -sSL "http://synpuf250.omopv4_plus.data.jsaw.io" | gunzip -c | psql -U postgres -d synpuf_250_20160815 > /tmp/restore.log 2>&1
before_script:
  - bundle exec rake diagnostics
script: bundle exec ruby test/all.rb
