language: ruby
rvm:
- 2.4
- 2.5
dist: trusty
sudo: false
gemfile: ".travis.gemfile"
env:
  global:
  - CONCEPTQL_DATA_MODEL=omopv4_plus SEQUELIZER_URI="postgres://localhost/synpuf_250_20160815?username=postgres"
  - secure: krTfSi0Itzy6NbTg3Fe/H/uyI5mjG6tYjE6G5zSmkl4ftmiDZ8ziI8YEXl5tnOlQtCPJxHzCLFlzfxFle11g+8at8WA7Fc3zwC+LEIDGV7HLG2dev4K18vM7sAtbvbFseprJGQZb1jWf7rez6ie3cp0K4SeLzRl5HWMyCj/HG3A=
  matrix:
  - CONCEPTQL_FORCE_TEMP_TABLES=true DOCKER_SCRATCH_DATABASE=scratch
  - CONCEPTQL_FORCE_TEMP_TABLES=false
addons:
  postgresql: '9.6'
  apt:
    packages:
    - python-pip
services:
- postgresql
before_install:
- gem install bundler tping
- sudo pip install pyOpenSSL cryptography idna certifi urllib3[secure] sqlparse
- find /var/ramfs/postgresql/9.{2,3,4,5} -maxdepth 0 -print | sudo xargs rm -rf
- df -h
- sudo service postgresql stop 9.6
- sudo bash -c "echo \"data_directory = '/etc/postgresql/9.6/main/data'\" >> /etc/postgresql/9.6/main/postgresql.conf"
- tail /etc/postgresql/9.6/main/postgresql.conf
- sudo -u postgres /usr/lib/postgresql/9.6/bin/initdb /etc/postgresql/9.6/main/data
- sudo service postgresql start 9.6
- psql -c 'create database synpuf_250_20160815;' -U postgres
- psql -c 'create schema scratch;' -U postgres -d synpuf_250_20160815
- curl -sSL "http://synpuf250.omopv4_plus.data.jsaw.io" | gunzip -c | psql -U postgres -d synpuf_250_20160815 > /tmp/restore.log 2>&1 || cat /tmp/restore.log
- df -h
before_script:
- bundle exec rake diagnostics
script: travis_wait 40 bundle exec ruby test/all.rb
notifications:
  slack:
    secure: YrvvLrIOgRIzqb01GbektA0YZXCieghuhaU3O4vBW/otrz26twb/0zeB/HHqKS3P2re0R127wGw6nAUAG9ieEHPYMKcpZZWzvnPrqQ/5ASbIZWX85fps0svFEeQTqRjK8TdHC/0ZJoy3P7i6wgBoWcs434aSR4K6KgisdWJATk0=

jobs:
  include:
    - stage: Ping Jigsaw Builder
      before_install: gem install tping
      before_script: skip
      script: tping $TRAVIS_PRO_TOKEN outcomesinsights jigsaw_builder pro

