language: ruby
rvm:
- 2.2
- 2.3
- 2.4
sudo: false
gemfile: ".travis.gemfile"
env:
- CONCEPTQL_DATA_MODEL=omopv4_plus SEQUELIZER_URI="postgres://localhost/synpuf_250_20160815?username=postgres"
addons:
  postgresql: '9.6'
  apt:
    packages:
      - python-pip
services:
- postgresql
before_install:
- gem install bundler
- pip install sqlparse
- psql -c 'create database synpuf_250_20160815;' -U postgres
- curl -sSL "http://synpuf250.omopv4_plus.data.jsaw.io" | gunzip -c | psql -U postgres
  -d synpuf_250_20160815 > /tmp/restore.log 2>&1
before_script:
- bundle exec rake diagnostics
script: bundle exec ruby test/all.rb
notifications:
  slack:
    secure: YrvvLrIOgRIzqb01GbektA0YZXCieghuhaU3O4vBW/otrz26twb/0zeB/HHqKS3P2re0R127wGw6nAUAG9ieEHPYMKcpZZWzvnPrqQ/5ASbIZWX85fps0svFEeQTqRjK8TdHC/0ZJoy3P7i6wgBoWcs434aSR4K6KgisdWJATk0=
